### ISSUE TITLE
What license is this dataset released under?

### ISSUE THREAD

**Issue by rctatman** [my89/imSitu#1]
I'm interested in reproducing the results from the Zhao et al 2017, but I'm worried about falling afoul of copyright. What license is this dataset released under? (For reference, COCO is released under [CC-BY 4.0](http://cocodataset.org/#termsofuse)).

Thanks!

**Comment by my89** [comment]
We do not have the license for any of the images in the collection. If your intention is just to reproduce the gender bias analysis from that paper, you shouldn't need to release the images in any way. If you wanted to reprint them for profit, then there is potential concern. Please pm me if you want to chat more about it.
