### ISSUE TITLE
ile "eval.py", line 192, in <module>     (top1, top5) = eval_file(args.system_output, eval_dataset, standard_encoder, image_sparsity)

### ISSUE THREAD

**Issue by Daudkhan95** [my89/imSitu#2]

**Comment by Daudkhan95** [comment]
how to solve this error

**Comment by my89** [comment]
Hi,

Can you please post the whole stack trace and give me some context about what you are doing? 

Mark

**Comment by Daudkhan95** [comment]
hello sir actulally sir  I m kind of noob in this field. Im just doing  step  by step but now this erroe appeard

**Comment by my89** [comment]
Not sure I can help without more information. So I'm closing the issue.

**Comment by Daudkhan95** [comment]
Hi,

It’s okay sir I sorted it out and thanks again to be in touch

Daud
